name: irc_dart
description: IRC client library for Dart.
version: 1.0.1
repository: https://github.com/kkazuo/dart-irc-client

environment:
  sdk: '>=3.1.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
